AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is a lambda service application used by a battleship game
Resources:
  BattleshipInitializeFunction:
    Type: AWS::Serverless::Function
    FunctionName: BattleshipInitializeFunction
    Properties:
      Handler: battleship::battleship.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: s3://cfbattleship/ec8b800a2e708a94bb9db371fd1ab98c
      Environment:
        Variables:
          S3_BUCKET: tyrkamotchkacfsambucket
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
